//
// Created by binabik on 19/12/2020.
//

#ifndef IMAC3_DG_INCLUDE_UTIL_EIGEN_HPP
#define IMAC3_DG_INCLUDE_UTIL_EIGEN_HPP

// Some warnings are generated by including Eigen.
#ifdef _MVC
    #pragma warning(push, 0)
#elif defined(__GNUC__)
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wold-style-cast"
    #pragma GCC diagnostic ignored "-Wconversion"
#endif
// matrices
#include <Eigen/Dense>
#ifdef _MVC
    #pragma warning(pop)
#elif defined(__GNUC__)
    #pragma GCC diagnostic pop
#endif

namespace td::util
{
    class EigenUtility
    {
       public:

        /** -- methods -- **/
        template <class Point_T>
        [[nodiscard]] inline static
        Eigen::Matrix<typename Point_T::Scalar, Point_T::dimension, 1>
        dgtalPointToColumnVector(Point_T const & point);


    };
}

#include "eigen.inl"

#endif  // IMAC3_DG_INCLUDE_UTIL_EIGEN_HPP
